# -*- mode: python -*-

Import("env")

env = env.Clone()

#hack before we clean up includes
#env.AppendUnique( CPPDEFINES=[ 'BOOST_NO_IOSTREAM' ] )

env.Library(
    target="codegen",
    source=[
        "anta/Analysis.cpp",
        "anta/Cloner.cpp",
        "anta/CodeGenCtx.cpp",
        "anta/DebugPrint.cpp",
        "anta/Expr.cpp",
        "anta/Factory.cpp",
        "anta/Function.cpp",
        "anta/InlineFunction.cpp",
        "anta/InlineMFunc.cpp",
        "anta/LowerForLoop.cpp",
        "anta/LowerMFunc.cpp",
        "anta/ReplaceStmt.cpp",
        "anta/Scope.cpp",
        "anta/Statement.cpp",
        "anta/Type.cpp",

    	"machine/jitter.cpp",

    	"operator/aggregates.cpp",
        "operator/common.cpp",
        "operator/collection_scan.cpp",
        "operator/entry_functions.cpp",
        "operator/hash_aggregation.cpp",
        "operator/operator.cpp",
        "operator/project.cpp",

        "test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
    ],
)
